### ISSUE TITLE
Replace 6's with NA for tremor and slowness variables in syn20822276.

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#11]
Replace 6's with NA for tremor and slowness variables in syn20822276.

Edit: Also, for slowness_walking only, please replace "0" with NAs as well.

**Comment by philerooski** [comment]
Can you help me understand why you think these are errors? About 1/4th of the values for slowness and over 1/3 of the values for tremor are 6's.

**Comment by sieberts** [comment]
They're not errors, but 6 in the this table means NA, so it's better to replace 6's with NA to avoid confusion for anyone using the data.

**Comment by philerooski** [comment]
done

**Comment by sieberts** [comment]
This doesn't appear to be done correctly. I still see 6's in the table.

**Comment by sieberts** [comment]
Also, for slowness_walking only, please replace "0" with NAs as well.

**Comment by philerooski** [comment]
Huh, that was weird. I must have accidentally stored the original table back to itself. 

I've done
tremor: 6 -> NA
slowness_walking: 0 -> NA, 6 -> NA

If everything looks kosher can you close this issue for me?

**Comment by sieberts** [comment]
Looks good. Thanks!
